version: '3'
services:
    app:
        image: node:14
        command: bash -c "npm && npm start"
        restart: unless-stopped
        volumes:
            - '.:/usr/src/app'
        working_dir: /usr/src/app
        ports:
            - '4444:4444'
        links:
            - mongo
    mongo:
        restart: unless-stopped
        image: mongo
        ports:
            - '27017:27017'
